### PR TITLE
Improvement: Implement GET document endpoint. RD-24577

### PR DESCRIPTION
**Pull request by ytuauden**
https://jira.ringcentral.com/browse/RD-24577

### CODE REVIEW

**Comment by ytuauden** [comment]
@ylecuyer I also removed all projections from the gem since they are not supported anymore by LinkedIn

**Comment by ylecuyer** [comment]
> @ylecuyer I also removed all projections from the gem since they are not supported anymore by LinkedIn
could you split the project stuff in another PR ?

**Comment by ytuauden** [comment]
> > @ylecuyer I also removed all projections from the gem since they are not supported anymore by LinkedIn
> 
> could you split the project stuff in another PR ?

sure, should I create a ticket as well ?

**Comment by ylecuyer** [comment]
>  sure, should I create a ticket as well ?

Not needed, lets just make a PR here

**Comment by ylecuyer** [comment]
LGTM

**Pull request merged**
